// 仕分けで指を動かしている最中に画面が隠れ、戻って「タップで再開」したら、勝手に仕分けられるか
import { open, OUT } from './fix1_common.mjs';
const { browser, page, errors, H, tap, top, hide, active } = await open('?scene=Sort&wave=1&seed=3');
await page.waitForFunction(() => window.__sh && window.__sh.key === 'Sort', null, { timeout: 20000 });
await page.evaluate(() => window.__sh.skipIntro());
await page.waitForFunction(() => { const s = window.__sh.state(); return s.state === 'play' && !s.locked; }, null, { timeout: 10000 });
const before = await page.evaluate(() => window.__sh.state());
console.log('before', before.idx, JSON.stringify(before.sorts));
const cdp = await page.context().newCDPSession(page);
const r = await page.evaluate(() => { const b = window.__game.canvas.getBoundingClientRect(); return { l: b.left, t: b.top, w: b.width, h: b.height }; });
const P = (x, y) => ({ x: r.l + (x * r.w) / 216, y: r.t + (y * r.h) / H });
const s0 = P(108, 150);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...s0, id: 1 }] });
await page.waitForTimeout(50);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: s0.x - 15, y: s0.y, id: 1 }] });
await page.waitForTimeout(50);
console.log('dragging', await page.evaluate(() => ({ pid: window.__sh.scene.swipe.pointerId, x: window.__sh.scene.card.x })));
await hide(true);
await page.waitForTimeout(100);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
await page.waitForTimeout(300);
await hide(false);
await page.waitForTimeout(500);
console.log('scenes while paused', await active(), await page.evaluate(() => ({ pid: window.__sh.scene.swipe.pointerId, x: window.__sh.scene.card.x, bad: window.__sh.scene.btnBad.pressed })));
// 右のほうをタップして再開
const t = P(190, 150);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...t, id: 2 }] });
await page.waitForTimeout(80);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
await page.waitForTimeout(600);
const after = await page.evaluate(() => window.__sh.state());
console.log('after', after.idx, JSON.stringify(after.sorts), 'scenes', await active());
await page.screenshot({ path: OUT + '/t5_after.png' });
console.log(errors.filter(e => !e.includes('WebGL') && !e.includes('GPU stall')).join('\n') || 'no errors');
await browser.close();
