import { open } from './fix1_common.mjs';
const { browser, page, errors, hide, active } = await open('?seed=77');
await page.waitForTimeout(1500);
await page.keyboard.press('Enter');
await page.waitForFunction(() => window.__game.scene.isActive('UiWipe'), null, { timeout: 5000, polling: 5 });
await hide(true);
await page.waitForTimeout(2000);
console.log('hidden 2s', await active());
await hide(false);
await page.waitForTimeout(1500);
console.log('visible 1.5s', await active());
console.log(errors.filter(e => !e.includes('WebGL') && !e.includes('GPU')).join('\n') || 'no errors');
await browser.close();
