import { open } from './fix1_common.mjs';
const { browser, page, H, hide } = await open('?scene=Sort&wave=1&seed=3');
await page.waitForFunction(() => window.__sh && window.__sh.key === 'Sort', null, { timeout: 20000 });
await page.evaluate(() => window.__sh.skipIntro());
await page.waitForFunction(() => { const s = window.__sh.state(); return s.state === 'play' && !s.locked; }, null, { timeout: 10000 });
const cdp = await page.context().newCDPSession(page);
const r = await page.evaluate(() => { const b = window.__game.canvas.getBoundingClientRect(); return { l: b.left, t: b.top, w: b.width, h: b.height }; });
const P = (x, y) => ({ x: r.l + (x * r.w) / 216, y: r.t + (y * r.h) / H });
const b = (await page.evaluate(() => window.__sh.buttons()))[0];
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...P(b.x, b.y), id: 1 }] });
await page.waitForTimeout(30);
console.log('pressed while down', await page.evaluate(() => window.__sh.scene.btnBad.pressed));
await hide(true);
await page.waitForTimeout(50);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
await page.waitForTimeout(200);
await hide(false);
await page.waitForTimeout(500);
console.log('pressed while paused', await page.evaluate(() => window.__sh.scene.btnBad.pressed));
await browser.close();
