import { open } from './fix1_common.mjs';
const { browser, page, H } = await open('?scene=Sort&wave=1&seed=3');
await page.waitForFunction(() => window.__sh && window.__sh.key === 'Sort', null, { timeout: 20000 });
await page.evaluate(() => window.__sh.skipIntro());
await page.waitForFunction(() => { const s = window.__sh.state(); return s.state === 'play' && !s.locked; }, null, { timeout: 10000 });
const cdp = await page.context().newCDPSession(page);
const r = await page.evaluate(() => { const b = window.__game.canvas.getBoundingClientRect(); return { l: b.left, t: b.top, w: b.width, h: b.height, iw: innerWidth }; });
console.log(r, H);
const P = (x, y) => ({ x: r.l + (x * r.w) / 216, y: r.t + (y * r.h) / H });
const s0 = P(108, 150);
await page.evaluate(() => { window.__ev = []; for (const t of ['touchstart','pointerdown','mousedown']) window.__game.canvas.addEventListener(t, (e) => window.__ev.push(t)); });
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...s0, id: 1 }] });
await page.waitForTimeout(100);
console.log(await page.evaluate(() => ({ ev: window.__ev, p: window.__game.input.pointers.map(p => [p.id, p.isDown, Math.round(p.x), Math.round(p.y)]), pid: window.__sh.scene.swipe.pointerId })));
await browser.close();
